/**
 * Code Generation & Export Logic
 * Converts the canvas state tree into literal HTML, CSS, JS text.
 */

document.addEventListener('DOMContentLoaded', () => {
    let generatedHTML = '';
    let generatedCSS = '';
    let generatedJS = `// Auto-generated interactions\nconsole.log('NeuroForg site ready');\n`;
    let liveTab = 'html';

    const btnExport = document.getElementById('btn-export');
    const btnPreview = document.getElementById('btn-preview');
    const modal = document.getElementById('export-modal');
    const editor = document.getElementById('code-editor');
    const liveCodeView = document.getElementById('live-code-view');
    const btnApplyManual = document.getElementById('btn-apply-manual-code');
    const btnResetCode = document.getElementById('btn-reset-code');

    let isManualMode = false;
    let manualHTML = '';
    let manualCSS = '';
    let manualJS = '';

    btnExport.addEventListener('click', () => {
        generateCode();
        modal.classList.add('active');
        window.updateExportModal('html');
    });

    btnPreview.addEventListener('click', () => {
        // Just open the generated contents in a new tab
        generateCode();
        const win = window.open();
        const settings = window.BuilderState.pageSettings || {};
        const html = isManualMode ? manualHTML : generatedHTML;
        const css = isManualMode ? manualCSS : generatedCSS;
        const js = isManualMode ? manualJS : generatedJS;

        win.document.write(`
            <!DOCTYPE html>
            <html>
            <head>
                <style>
                    @import url('https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&display=swap');
                    body {
                        margin: 0;
                        font-family: 'Manrope', sans-serif;
                        background: ${settings.background};
                        color: ${settings.textColor};
                    }
                    * { box-sizing: border-box; }
                    ${css}
                </style>
            </head>
            <body>
                ${html}
                <script>${js}</script>
            </body>
            </html>
        `);
        win.document.close();
    });

    function generateCode() {
        if (isManualMode) return; // Don't overwrite manual edits

        let cssRules = [];
        let htmlContent = '';
        const pageSettings = window.BuilderState.pageSettings || {};

        const processNode = (comp) => {
            // CSS classes generated by ID
            let styleStrs = [];
            for (let [key, val] of Object.entries(comp.styles)) {
                if (val) { // Ignore empty rules
                    // camelCase to kebab-case
                    const kebab = key.replace(/([a-z0-9]|(?=[A-Z]))([A-Z])/g, '$1-$2').toLowerCase();
                    styleStrs.push(`    ${kebab}: ${val};`);
                }
            }
            const compId = comp.id || 'el_' + Math.random().toString(36).substring(2, 9);
            if (styleStrs.length > 0) {
                // Remove the 'el_' prefix from ID to make a valid class name
                const className = compId.replace('el_', 'cls_');
                cssRules.push(`.${className} {\n${styleStrs.join('\n')}\n}`);
            }

            // HTML Strings
            const className = compId.replace('el_', 'cls_');
            const classAttr = `class="${comp.props?.className ? comp.props.className + ' ' : ''}${className}"`;
            
            let tag = 'div';
            let content = '';
            let attrs = classAttr;

            switch (comp.type) {
                case 'Heading':
                    tag = comp.props.level || 'h2';
                    content = comp.props.text;
                    break;
                case 'Paragraph':
                    tag = 'p';
                    content = comp.props.text;
                    break;
                case 'Button':
                    tag = 'a';
                    attrs += ` href="${comp.props.href || '#'}"`;
                    content = comp.props.text;
                    break;
                case 'SearchBar':
                    tag = 'div';
                    content = `\n  <input type="text" placeholder="${comp.props.placeholder}" style="width:100%;border:none;background:transparent;outline:none;font:inherit;" />\n`;
                    break;
                case 'Video':
                    tag = 'video';
                    attrs += ` src="${comp.props.src}"`;
                    if(comp.props.controls) attrs += ' controls';
                    if(comp.props.autoplay) attrs += ' autoplay';
                    if(comp.props.loop) attrs += ' loop';
                    return `\n<${tag} ${attrs}></${tag}>`;
                case 'Image':
                    return `\n<img ${attrs} src="${comp.props.src}" alt="${comp.props.alt || 'Image'}" />`;
                case 'Form':
                    tag = 'form';
                    if (comp.children && comp.children.length > 0) {
                        content = comp.children.map(child => processNode(child)).join('');
                    }
                    break;
                case 'Navbar':
                    tag = 'nav';
                    if (comp.children && comp.children.length > 0) {
                        content = comp.children.map(child => processNode(child)).join('');
                    }
                    break;
                case 'Card':
                    tag = 'section';
                    if (comp.children && comp.children.length > 0) {
                        content = comp.children.map(child => processNode(child)).join('');
                    }
                    break;
                case 'Container':
                default:
                    tag = 'div';
                    if (comp.children && comp.children.length > 0) {
                        content = comp.children.map(child => processNode(child)).join('');
                    }
                    break;
            }

            return `\n<${tag} ${attrs}>${content}</${tag}>`;
        };

        htmlContent = window.BuilderState.components.map(comp => processNode(comp)).join('');

        generatedHTML = htmlContent.trim();
        generatedCSS = [
            `/* Auto-Generated by NeuroForg Pro */`,
            `body { background: ${pageSettings.background || '#f7f7f2'}; color: ${pageSettings.textColor || '#1f2937'}; }`,
            pageSettings.enable3d ? `/* 3D Engine Interactions */\n[class^="cls_"] { transform-style: preserve-3d; transition: transform 0.35s ease, box-shadow 0.35s ease; }\n[class^="cls_"]:hover { transform: translateY(-8px) rotateX(4deg) rotateY(-2deg); box-shadow: 0 20px 40px rgba(0, 0, 0, 0.2); }` : '',
            cssRules.join('\n\n')
        ].filter(Boolean).join('\n\n');

        generatedJS = [
            `// Auto-generated interactions`,
            `document.documentElement.dataset.theme = '${pageSettings.theme || 'light'}';`,
            `console.log('NeuroForg Pro site ready. Performance optimizations active.');`
        ].join('\n');

        manualHTML = generatedHTML;
        manualCSS = generatedCSS;
        manualJS = generatedJS;

        updateLiveCodeView();
    }

    // Manual Edit Handling
    liveCodeView.addEventListener('input', () => {
        isManualMode = true;
        btnApplyManual.innerHTML = `<i class='bx bx-refresh bx-spin'></i> Syncing...`;
        btnApplyManual.style.background = 'var(--accent-strong)';
        
        if (liveTab === 'html') manualHTML = liveCodeView.value;
        else if (liveTab === 'css') manualCSS = liveCodeView.value;
        else manualJS = liveCodeView.value;
    });

    btnApplyManual.addEventListener('click', () => {
        applyCodeToIframe();
        btnApplyManual.innerHTML = `<i class='bx bx-check-double'></i> Applied!`;
        btnApplyManual.style.background = 'var(--success)';
        setTimeout(() => {
            btnApplyManual.innerHTML = `<i class='bx bx-check-double'></i> Apply Code`;
        }, 1500);
    });

    btnResetCode?.addEventListener('click', () => {
        if (confirm('Discard manual edits and reset to visual builder state?')) {
            isManualMode = false;
            generateCode();
            if (window.showNotification) {
                window.showNotification('Reset Successful', 'Returned to visual builder state.', 'info');
            }
        }
    });

    function applyCodeToIframe() {
        const iframeDoc = iframe.contentDocument || iframe.contentWindow.document;
        const pageSettings = window.BuilderState.pageSettings || {};

        // Update CSS in iframe
        let styleTag = iframeDoc.getElementById('manual-style-tag');
        if (!styleTag) {
            styleTag = iframeDoc.createElement('style');
            styleTag.id = 'manual-style-tag';
            iframeDoc.head.appendChild(styleTag);
        }
        styleTag.textContent = manualCSS;

        // Update HTML in iframe
        iframeDoc.body.innerHTML = manualHTML;
        iframeDoc.body.style.background = pageSettings.background;
        iframeDoc.body.style.color = pageSettings.textColor;

        // Re-inject JS
        const oldScript = iframeDoc.getElementById('manual-js-tag');
        if (oldScript) oldScript.remove();
        const script = iframeDoc.createElement('script');
        script.id = 'manual-js-tag';
        script.textContent = manualJS;
        iframeDoc.body.appendChild(script);

        // Show notification
        if (window.showNotification) {
            window.showNotification('Code Applied', 'Your manual changes are now live on the canvas.', 'success');
        }
    }

    // Expose functionality to switch tabs
    window.updateExportModal = function(tab) {
        if (!isManualMode) generateCode();
        if (tab === 'html') editor.value = isManualMode ? manualHTML : generatedHTML;
        else if (tab === 'css') editor.value = isManualMode ? manualCSS : generatedCSS;
        else if (tab === 'js') editor.value = isManualMode ? manualJS : generatedJS;
    };

    window.BuilderExport = {
        generateCode,
        getCode() {
            generateCode();
            return {
                html: generatedHTML,
                css: generatedCSS,
                js: generatedJS
            };
        },
        getHTMLDocument() {
            generateCode();
            const siteName = window.BuilderState?.pageSettings?.siteName || 'NeuroForg Pro Site';
            return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${siteName}</title>
    <!-- SEO Auto-Optimization -->
    <meta name="description" content="Generated by NeuroForg Pro. This site is fully optimized for speed and search engines.">
    <meta name="robots" content="index, follow">
    <!-- <meta http-equiv="Content-Security-Policy" content="default-src 'self';"> -->
    <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;700&family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
    <style>
        body { margin: 0; padding: 0; font-family: 'Inter', sans-serif; overflow-x: hidden; }
        * { box-sizing: border-box; }
        ${generatedCSS}
    </style>
</head>
<body>
    ${generatedHTML}
    <script>
        ${generatedJS}
    </script>
</body>
</html>`;
        }
    };

    function updateLiveCodeView() {
        if (!liveCodeView) return;
        if (liveTab === 'html') liveCodeView.value = isManualMode ? manualHTML : generatedHTML;
        else if (liveTab === 'css') liveCodeView.value = isManualMode ? manualCSS : generatedCSS;
        else liveCodeView.value = isManualMode ? manualJS : generatedJS;
    }

    document.querySelectorAll('.live-tab-btn').forEach(btn => {
        btn.addEventListener('click', (event) => {
            document.querySelectorAll('.live-tab-btn').forEach(tab => tab.classList.remove('active'));
            event.currentTarget.classList.add('active');
            liveTab = event.currentTarget.dataset.liveTab;
            updateLiveCodeView();
        });
    });

    document.getElementById('btn-copy').addEventListener('click', () => {
        editor.select();
        document.execCommand('copy');
        alert('Code copied to clipboard!');
    });

    document.getElementById('btn-download').addEventListener('click', () => {
        const finalFile = window.BuilderExport.getHTMLDocument();
        const blob = new Blob([finalFile], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'website.html';
        a.click();
        URL.revokeObjectURL(url);
    });

    window.BuilderState.subscribe(() => {
        generateCode();
    });

    window.addEventListener('builderActivity', () => {
        if (isManualMode) {
            if (confirm('A change was made in the visual builder. Do you want to overwrite your manual code edits with the new layout?')) {
                isManualMode = false;
                generateCode();
            }
        }
    });

    generateCode();
});
