# Generated by Django 6.0.3 on 2026-03-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aiinteraction_model_used_aiinteraction_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='api_key_openai',
        ),
        migrations.DeleteModel(
            name='AIInteraction',
        ),
    ]
